# Site settings
title: Life.CEO
header-img: img/cover-beach.jpg
email: sjmscott@gmail.com
description: "Explorations, Discoveries, and Directions"
baseurl: ""
url: "www.life.ceo"
google_analytics:  UA-61254493-1  
twitter_username: sscotty
github_username:  sjmscott
facebook_username:  
# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
