# Site settings
title: Life.CEO
email: sjmscott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring the many dimensions of life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "life.ceo" # the base hostname & protocol for your site
twitter_username: sscotty
github_username:  sjmscott

# Build settings
markdown: kramdown

# Google Anaylytics
https://www.google.com/analytics/


google_analytics_tracking_id: UA-61254493-1
