# Site settings
title: Life.CEO
header-img: img/home-bg.jpg
email: sjmscott@gmail.com
description: "Explorations, Dicoveries, and Directions"
baseurl: ""
url: "www.life.ceo"
twitter_username: sscotty
github_username:  sjmscott
facebook_username:  stevejscott

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
